#!/bin/bash
# Remaining Encoder experiments

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_num_1.5.csv --num_scaling 1.5 --op_scaling 1 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_num_1.5.csv --num_scaling 1 --op_scaling 1.5 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_num_1.8.csv --num_scaling 1.8 --op_scaling 1 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_num_1.8.csv --num_scaling 1 --op_scaling 1.8 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_num_2.csv --num_scaling 2 --op_scaling 1 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_num_2.csv --num_scaling 1 --op_scaling 2 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder


#With explanation
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_0.7_0.7.csv --num_scaling 0.7 --op_scaling 0.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.3_0.7.csv --num_scaling 1.3 --op_scaling 0.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.7_0.7.csv --num_scaling 1.7 --op_scaling 0.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_2_0.7.csv --num_scaling 2 --op_scaling 0.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_0.7_1.3.csv --num_scaling 0.7 --op_scaling 1.3 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.3_1.3.csv --num_scaling 1.3 --op_scaling 1.3 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.7_1.3.csv --num_scaling 1.7 --op_scaling 1.3 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_2_1.3.csv --num_scaling 2 --op_scaling 1.3 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_0.7_1.7.csv --num_scaling 0.7 --op_scaling 1.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.3_1.7.csv --num_scaling 1.3 --op_scaling 1.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.7_1.7.csv --num_scaling 1.7 --op_scaling 1.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_2_1.7.csv --num_scaling 2 --op_scaling 1.7 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_0.7_2.csv --num_scaling 0.7 --op_scaling 2 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.3_2.csv --num_scaling 1.3 --op_scaling 2 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_1.7_2.csv --num_scaling 1.7 --op_scaling 2--modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/with/inference_both_2_2.csv --num_scaling 2 --op_scaling 2 --modification "Please solve the following problem and give a concise explanation with the answer at the end with \"The answer is: \"." --model_part encoder


#Without explanation
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_0.7_0.7.csv --num_scaling 0.7 --op_scaling 0.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". "
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.3_0.7.csv --num_scaling 1.3 --op_scaling 0.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.7_0.7.csv --num_scaling 1.7 --op_scaling 0.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_2_0.7.csv --num_scaling 2 --op_scaling 0.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_0.7_1.3.csv --num_scaling 0.7 --op_scaling 1.3 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.3_1.3.csv --num_scaling 1.3 --op_scaling 1.3 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.7_1.3.csv --num_scaling 1.7 --op_scaling 1.3 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder 
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_2_1.3.csv --num_scaling 2 --op_scaling 1.3 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_0.7_1.7.csv --num_scaling 0.7 --op_scaling 1.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.3_1.7.csv --num_scaling 1.3 --op_scaling 1.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.7_1.7.csv --num_scaling 1.7 --op_scaling 1.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_2_1.7.csv --num_scaling 2 --op_scaling 1.7 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder

python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_0.7_2.csv --num_scaling 0.7 --op_scaling 2 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.3_2.csv --num_scaling 1.3 --op_scaling 2 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_1.7_2.csv --num_scaling 1.7 --op_scaling 2--modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder
python src/flan_t5_attention_mod.py --model google/flan-t5-base --output results/attention_experiments-mmiqc/base/encoder/without/inference_both_2_2.csv --num_scaling 2 --op_scaling 2 --modification "Please solve the following problem and only output the answer at the end with \"The answer is: \". " --model_part encoder